sudo: false
language: python
services:
    - mongodb

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.7-dev
  include:
    - env: TOXENV=flake8
    - env: TOXENV=pylint
    - env: TOXENV=doc8
    - env: TOXENV=packaging
    - env: TOXENV=docs

install:
  - pip install tox
before_script:
  - sleep 15
  - mongo metaopt --eval 'db.createUser({user:"user",pwd:"pass",roles:["readWrite"]});'
script:
  - tox -e py
after_success:
  - tox -e final-coverage
  - tox -e codecov

# deploy:
#   skip_cleanup: true
#   provider: pypi
#   user: "..."
#   password:
#     secure: "..."
#   on:
#     branch: master
#   distributions: "sdist bdist_wheel"
